/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UserNoticeRouteImport } from './routes/user-notice'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SellTutorialRouteImport } from './routes/sell-tutorial'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RealNameRouteImport } from './routes/real-name'
import { Route as PaymentPasswordRouteImport } from './routes/payment-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as BuyTutorialRouteImport } from './routes/buy-tutorial'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNoticeRoute = UserNoticeRouteImport.update({
  id: '/user-notice',
  path: '/user-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTutorialRoute = SellTutorialRouteImport.update({
  id: '/sell-tutorial',
  path: '/sell-tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RealNameRoute = RealNameRouteImport.update({
  id: '/real-name',
  path: '/real-name',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPasswordRoute = PaymentPasswordRouteImport.update({
  id: '/payment-password',
  path: '/payment-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTutorialRoute = BuyTutorialRouteImport.update({
  id: '/buy-tutorial',
  path: '/buy-tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/buy-tutorial': typeof BuyTutorialRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/payment-password': typeof PaymentPasswordRoute
  '/real-name': typeof RealNameRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/sell-tutorial': typeof SellTutorialRoute
  '/trade': typeof TradeRoute
  '/transactions': typeof TransactionsRoute
  '/user-notice': typeof UserNoticeRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/buy-tutorial': typeof BuyTutorialRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/payment-password': typeof PaymentPasswordRoute
  '/real-name': typeof RealNameRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/sell-tutorial': typeof SellTutorialRoute
  '/trade': typeof TradeRoute
  '/transactions': typeof TransactionsRoute
  '/user-notice': typeof UserNoticeRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/buy-tutorial': typeof BuyTutorialRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/payment-password': typeof PaymentPasswordRoute
  '/real-name': typeof RealNameRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/sell-tutorial': typeof SellTutorialRoute
  '/trade': typeof TradeRoute
  '/transactions': typeof TransactionsRoute
  '/user-notice': typeof UserNoticeRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy'
    | '/buy-tutorial'
    | '/collection'
    | '/dashboard'
    | '/home'
    | '/payment-password'
    | '/real-name'
    | '/referral'
    | '/register'
    | '/sell'
    | '/sell-tutorial'
    | '/trade'
    | '/transactions'
    | '/user-notice'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy'
    | '/buy-tutorial'
    | '/collection'
    | '/dashboard'
    | '/home'
    | '/payment-password'
    | '/real-name'
    | '/referral'
    | '/register'
    | '/sell'
    | '/sell-tutorial'
    | '/trade'
    | '/transactions'
    | '/user-notice'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/buy'
    | '/buy-tutorial'
    | '/collection'
    | '/dashboard'
    | '/home'
    | '/payment-password'
    | '/real-name'
    | '/referral'
    | '/register'
    | '/sell'
    | '/sell-tutorial'
    | '/trade'
    | '/transactions'
    | '/user-notice'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  BuyTutorialRoute: typeof BuyTutorialRoute
  CollectionRoute: typeof CollectionRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  PaymentPasswordRoute: typeof PaymentPasswordRoute
  RealNameRoute: typeof RealNameRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  SellRoute: typeof SellRoute
  SellTutorialRoute: typeof SellTutorialRoute
  TradeRoute: typeof TradeRoute
  TransactionsRoute: typeof TransactionsRoute
  UserNoticeRoute: typeof UserNoticeRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-notice': {
      id: '/user-notice'
      path: '/user-notice'
      fullPath: '/user-notice'
      preLoaderRoute: typeof UserNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-tutorial': {
      id: '/sell-tutorial'
      path: '/sell-tutorial'
      fullPath: '/sell-tutorial'
      preLoaderRoute: typeof SellTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-name': {
      id: '/real-name'
      path: '/real-name'
      fullPath: '/real-name'
      preLoaderRoute: typeof RealNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-password': {
      id: '/payment-password'
      path: '/payment-password'
      fullPath: '/payment-password'
      preLoaderRoute: typeof PaymentPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tutorial': {
      id: '/buy-tutorial'
      path: '/buy-tutorial'
      fullPath: '/buy-tutorial'
      preLoaderRoute: typeof BuyTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  BuyTutorialRoute: BuyTutorialRoute,
  CollectionRoute: CollectionRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  PaymentPasswordRoute: PaymentPasswordRoute,
  RealNameRoute: RealNameRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  SellRoute: SellRoute,
  SellTutorialRoute: SellTutorialRoute,
  TradeRoute: TradeRoute,
  TransactionsRoute: TransactionsRoute,
  UserNoticeRoute: UserNoticeRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
